# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Build

# Controls when the action will run. 
on: 
  #push:                       # Runs on push events
  #pull_request:               # Runs on pull requests
  workflow_dispatch:          # Allows you to run this workflow manually from the Actions tab

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MLM_LICENSE_TOKEN }}
  
jobs:

  # This workflow contains two jobs called "test" and "compile-webapp"
  test:
    # This job will run for all the OS present in the matrix
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
     
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
 
    steps:
      - uses: actions/checkout@v4
       
      - name: Setup MATLAB on the GitHub Actions runner
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
 
      - name: Run ${{ matrix.os }} build to create MEX file and run tests on it
        uses: matlab-actions/run-build@v2
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
 
